language: python
sudo: false
matrix:
  include:
   - python: 2.7
     env: TOXENV=py27
   - python: 3.4
     env: TOXENV=py34
   - python: 3.5
     env: TOXENV=py35
   - python: 3.6
     env: TOXENV=py36
   - python: 3.7
     env: TOXENV=py37
   - python: pypy
     env: TOXENV=pypy
   - python: 3.7
     env: TOXENV=flake8
install:
  - pip install tox
  - if test "$TOXENV" = py37 ; then pip install coveralls ; fi
script: tox
after_script:
  - if test "$TOXENV" = py37 ; then coveralls ; fi
